spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    #decirle al servidor que no se registre en el registro del servicio
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0    #tiempo de espera para la sincronización posterior
