server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: gameRoute #Identificando la ruta del service de producto
          uri: lb://game-service  #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/games/**
        - id: libraryRoute #Identificando la ruta del service de producto
          uri: lb://library-service #URL donde se har치 el redirect segun el predicate definido
          predicates: #RReglas de an치lisis de una request
            - Path=/libraries/**
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway
       
info:
  app:
    name: gateway-service
    description: Gateway Service created for DH
    version: 1.0.0
