spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
    
eureka :
    cliente :
      servicio-url :
        zona predeterminada : http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

