primavera :
  cremallera :
    habilitado : verdadero
    baseUrl : http://localhost:9411/zipkin
    
eureka :
    cliente :
      servicio-url :
        zona predeterminada : http://localhost:8761/eureka
      
gesti贸n :
  puntos finales :
    web :
      exposici贸n :
        incluir : " * "
  informaci贸n :
    env :
      habilitado : verdadero
  punto final :
    informaci贸n :
      habilitado : verdadero
