server:
  port: 8082

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/tp_final
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:movie.sql

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Movie Microservice
